query General {
  general {
    nombre
    descripcion
    banner {
      id
      title
    }
  }

  menus {
    nombre
    paginas {
      paginas_id {
        slug
        titulo
      }
    }
  }
}
