query General {
  general {
    nombre
    descripcion
    banner {
      id
      title
    }
    texto_footer
  }

  paginas(filter: { estado: { _eq: "publicado" } }, sort: ["sort"]) {
    titulo
    slug
  }

  paginas_archivo(filter: { estado: { _eq: "publicado" } }, sort: ["sort"]) {
    titulo
    titulo_singular
    slug
    mostrar_en_menu
    coleccion
  }
}
